name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Ensure executable permission for VuePress
        run: chmod +x ./node_modules/.bin/vuepress

      - name: Build VuePress site
        run: ./node_modules/.bin/vuepress build docs
        
      - name: Add CNAME for Custom Domain
        run: cp CNAME docs/.vuepress/dist/

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: builds
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
